### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by nunojesus** [zswang/jcameras#1]
Hi, I like your project, and as a opensource contributer, I would like to contribute to this project with a  logo design if you want.

Greetings

Nuno Jesus

**Comment by zswang** [comment]
Sure. I want a logo to this project.

Thank you.

![image](https://user-images.githubusercontent.com/536587/40236726-09204c46-5ae1-11e8-83cf-4ecccc018bcb.png)
![image](https://user-images.githubusercontent.com/536587/40236749-21b2920a-5ae1-11e8-817b-92206d455e27.png)

**Comment by nunojesus** [comment]
Ok, that images are for inspiration? What do you want more? What colors you prefer?

**Comment by zswang** [comment]
inspiration

**Comment by nunojesus** [comment]
Hello, here is the logo I was creating for this project, for this one I was inspired by the two images that you put here.
Then this logo consists of a video camera and a mouse arrow, the circles around the arrow means a click of the mouse and the red circle means the red light of video recording.

I hope you like it if you want some change just say something.

![jcameras](https://user-images.githubusercontent.com/34600369/40256930-298e9e30-5ae4-11e8-9d93-dc51593a814a.png)

**Comment by zswang** [comment]
I really like your design.

I hope the following pointer is more like an image and the whole is like a square

![snip20180519_123](https://user-images.githubusercontent.com/536587/40265343-04c01ad6-5b69-11e8-8a34-bdfd98a90b6c.png)

Thank you very much.

**Comment by nunojesus** [comment]
Hi, it looks good the changes, so the the mouse arrow keeps like that.
I dont understand this "whole is like a square"

**Comment by zswang** [comment]
![snip20180519_126](https://user-images.githubusercontent.com/536587/40267629-526a2672-5b92-11e8-9772-b69ebe4b505c.png)

**Comment by nunojesus** [comment]
So you want the logo as the picture you send me right? i will try to do it tonight.

**Comment by zswang** [comment]
Yes, I want.

**Comment by nunojesus** [comment]
see if is this what you want.

![sem titulo-1](https://user-images.githubusercontent.com/34600369/40272194-c3e607f8-5ba1-11e8-9d9a-86be354063ea.png)

**Comment by zswang** [comment]
Yes, officially what I want.

Thanks again.

**Comment by nunojesus** [comment]
Ok, I will send you the png files, do you want other formats, like svg, eps???
From the 2 imagens you prefer the one that have the dot or the other one?
Greetings.

**Comment by zswang** [comment]
All that is needed has been got.
